"use client";
import {useEffect,useState} from "react";
const api=()=>process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
export default function Dashboard(){
 const [user,setUser]=useState<any>(); const [tenant,setTenant]=useState<any>(); const [services,setServices]=useState<any[]>([]); const [products,setProducts]=useState<any[]>([]);
 const [customers,setCustomers]=useState<any[]>([]); const [calls,setCalls]=useState<any[]>([]); const [tab,setTab]=useState("overview"); const [selectedCall,setSelectedCall]=useState<any>(null);
 useEffect(()=>{const u=localStorage.getItem("ago_user"),t=localStorage.getItem("ago_tenant");if(!u){location.href="/login";return}setUser(JSON.parse(u));setTenant(t?JSON.parse(t):null)},[]);
 async function load(){if(!tenant)return;const h={Authorization:"Bearer "+localStorage.getItem("ago_access_token")};const [s,p,c,ca]=await Promise.all([fetch(api()+"/api/v1/tenants/"+tenant.id+"/services",{headers:h}),fetch(api()+"/api/v1/tenants/"+tenant.id+"/products",{headers:h}),fetch(api()+"/api/v1/tenants/"+tenant.id+"/customers",{headers:h}),fetch(api()+"/api/v1/tenants/"+tenant.id+"/calls",{headers:h})]);setServices((await s.json()).items||[]);setProducts((await p.json()).items||[]);setCustomers((await c.json()).items||[]);setCalls((await ca.json()).items||[])}
 useEffect(()=>{load()},[tenant]);
 async function add(kind:string){const name=prompt("New "+kind+" name");if(!name||!tenant)return;const h={"Content-Type":"application/json",Authorization:"Bearer "+localStorage.getItem("ago_access_token")};await fetch(api()+"/api/v1/tenants/"+tenant.id+"/"+kind+"s",{method:"POST",headers:h,body:JSON.stringify({name,price:0,currency:"INR",is_active:true})});load()}
 async function openCall(c:any){if(!tenant)return;const h={Authorization:"Bearer "+localStorage.getItem("ago_access_token")};const r=await fetch(api()+"/api/v1/tenants/"+tenant.id+"/calls/"+c.id+"/context",{headers:h});setSelectedCall(await r.json())}
 async function handoff(c:any){if(!tenant)return;const h={Authorization:"Bearer "+localStorage.getItem("ago_access_token")};await fetch(api()+"/api/v1/tenants/"+tenant.id+"/calls/"+c.id+"/handoff",{method:"POST",headers:h});load();openCall(c)}
 if(!user)return <main className="shell"><div className="card">Loading workspace...</div></main>;
 return <main className="shell"><div className="hero"><p>AI GROWTH OS</p><h1>{tenant?.name||"Business Dashboard"}</h1><p>AI customer engagement, CRM, calls, routing and growth in one workspace.</p></div>
 <nav className="tabs">{["overview","catalog","customers","brain","calls"].map(x=><button key={x} onClick={()=>setTab(x)}>{x}</button>)}<button onClick={()=>{localStorage.clear();location.href="/login"}}>Sign out</button></nav>
 {tab==="overview"&&<section className="grid"><div className="card"><b>Customers</b><h2>{customers.length}</h2><p>Identified CRM customers</p></div><div className="card"><b>AI Calls</b><h2>{calls.length}</h2><p>Voice interactions recorded</p></div><div className="card"><b>AI Brain</b><p>Approved business data, FAQs and controlled AI answers.</p></div><div className="card"><b>Human handoff</b><p>Route calls to the configured department and give staff the full customer context.</p></div></section>}
 {tab==="catalog"&&<section className="grid"><div className="card"><h2>Services</h2><button onClick={()=>add("service")}>Add service</button>{services.map(x=><p key={x.id}>{x.name} · {x.price??"—"} {x.currency}</p>)}</div><div className="card"><h2>Products</h2><button onClick={()=>add("product")}>Add product</button>{products.map(x=><p key={x.id}>{x.name} · {x.price??"—"} {x.currency}</p>)}</div></section>}
 {tab==="customers"&&<section className="grid"><div className="card"><h2>Customers</h2>{customers.map(x=><p key={x.id}><b>{x.name||"Unknown"}</b> · {x.phone}</p>)}</div><div className="card"><h2>CRM</h2><p>Customers created from PWA voice and chat can be linked to conversations and call records.</p></div></section>}
 {tab==="brain"&&<div className="card"><h2>Business Brain</h2><p>Approved knowledge and catalog data are used before the LLM. Unknown facts are not invented.</p></div>}
 {tab==="calls"&&<section className="grid"><div className="card"><h2>Live & recent calls</h2>{calls.length===0&&<p>No calls yet.</p>}{calls.map(c=><div key={c.id} style={{borderBottom:"1px solid #ddd",padding:"12px 0"}}><p><b>{c.status}</b> · {c.department||"routing pending"} · {c.intent||"unknown"}</p><p>{c.created_at?new Date(c.created_at).toLocaleString():""}</p><button onClick={()=>openCall(c)}>View context</button> <button onClick={()=>handoff(c)}>Request human</button></div>)}</div><div className="card"><h2>Staff context</h2>{selectedCall?<><p><b>Customer:</b> {selectedCall.customer?.name||"Not identified"}</p><p><b>Mobile:</b> {selectedCall.customer?.phone||"Not identified"}</p><p><b>Department:</b> {selectedCall.call.department||"Pending"}</p><p><b>Intent:</b> {selectedCall.call.intent||"Unknown"}</p><h3>Transcript</h3><pre style={{whiteSpace:"pre-wrap"}}>{selectedCall.call.transcript||"No transcript yet."}</pre></>:<p>Select a call to see the context a staff member would receive.</p>}</div></section>}
 </main>
}