"use client";
import {useEffect,useState} from "react";
const api=()=>process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
const featureLabels:any={digital_menu:"Digital Menu",online_ordering:"Online Ordering",order_tracking:"Order Tracking",call_waiter:"Call Waiter",service_requests:"Service Requests",games:"Mini Games",auto_bill:"Automatic Bill",online_payment:"Online Payment",ai_chat:"AI Chat",ai_voice:"AI Voice",loyalty:"Loyalty Program",referrals:"Referrals",feedback:"AI Feedback",google_review:"Google Review",bookings:"Bookings",queue:"Queue"};
export default function Dashboard(){
 const [tenant,setTenant]=useState<any>(null),[tab,setTab]=useState("overview"),[features,setFeatures]=useState<any>({}),[menu,setMenu]=useState<any>({categories:[],items:[]}),[orders,setOrders]=useState<any[]>([]),[requests,setRequests]=useState<any[]>([]),[rules,setRules]=useState<any[]>([]),[review,setReview]=useState(""),[status,setStatus]=useState("");
 const token=()=>localStorage.getItem("ago_access_token")||"";
 const headers=()=>({Authorization:"Bearer "+token()});
 async function load(){const t=tenant;if(!t)return;const h=headers();const [f,m,o,r,l,g]=await Promise.all([fetch(api()+"/api/v1/tenants/"+t.id+"/features",{headers:h}),fetch(api()+"/api/v1/tenants/"+t.id+"/menu",{headers:h}),fetch(api()+"/api/v1/tenants/"+t.id+"/orders",{headers:h}),fetch(api()+"/api/v1/tenants/"+t.id+"/service-requests",{headers:h}),fetch(api()+"/api/v1/tenants/"+t.id+"/loyalty-rules",{headers:h}),fetch(api()+"/api/v1/tenants/"+t.id+"/review-settings",{headers:h})]);if(f.ok)setFeatures((await f.json()).features||{});if(m.ok)setMenu(await m.json());if(o.ok)setOrders((await o.json()).items||[]);if(r.ok)setRequests((await r.json()).items||[]);if(l.ok)setRules((await l.json()).items||[]);if(g.ok)setReview((await g.json()).review_url||"");}
 useEffect(()=>{const raw=localStorage.getItem("ago_tenant");if(!raw){location.href="/login";return}setTenant(JSON.parse(raw))},[]);
 useEffect(()=>{if(!tenant)return;load();const id=window.setInterval(load,5000);return()=>clearInterval(id)},[tenant]);
 async function saveFeatures(){const r=await fetch(api()+"/api/v1/tenants/"+tenant.id+"/features",{method:"PUT",headers:{...headers(),"Content-Type":"application/json"},body:JSON.stringify({features})});setStatus(r.ok?"Feature settings saved":"Unable to save features");}
 async function saveReview(){const r=await fetch(api()+"/api/v1/tenants/"+tenant.id+"/review-settings",{method:"PUT",headers:{...headers(),"Content-Type":"application/json"},body:JSON.stringify({review_url:review})});setStatus(r.ok?"Google review settings saved":"Unable to save review settings");}
 async function addCategory(){const name=prompt("Category name");if(!name)return;await fetch(api()+"/api/v1/tenants/"+tenant.id+"/menu/categories",{method:"POST",headers:{...headers(),"Content-Type":"application/json"},body:JSON.stringify({name})});load();}
 async function addItem(){const name=prompt("Menu item name");if(!name)return;const price=Number(prompt("Price in INR","0")||0);await fetch(api()+"/api/v1/tenants/"+tenant.id+"/menu/items",{method:"POST",headers:{...headers(),"Content-Type":"application/json"},body:JSON.stringify({name,price})});load();}
 async function toggleItem(x:any){await fetch(api()+"/api/v1/tenants/"+tenant.id+"/menu/items/"+x.id,{method:"PATCH",headers:{...headers(),"Content-Type":"application/json"},body:JSON.stringify({is_available:!x.is_available})});load();}
 async function orderStatus(o:any,status:string){const r=await fetch(api()+"/api/v1/tenants/"+tenant.id+"/orders/"+o.id,{method:"PATCH",headers:{...headers(),"Content-Type":"application/json"},body:JSON.stringify({status})});if(!r.ok)setStatus("Unable to update order");load();}
 async function requestStatus(x:any,status:string){await fetch(api()+"/api/v1/tenants/"+tenant.id+"/service-requests/"+x.id,{method:"PATCH",headers:{...headers(),"Content-Type":"application/json"},body:JSON.stringify({status})});load();}
 async function addRule(){const event=prompt("Event type: purchase / game / referral / first_visit");if(!event)return;const name=prompt("Rule name","Reward")||"Reward";const points=Number(prompt("Points","10")||0);const minimum=Number(prompt("Minimum bill (0 for none)","0")||0);await fetch(api()+"/api/v1/tenants/"+tenant.id+"/loyalty-rules",{method:"POST",headers:{...headers(),"Content-Type":"application/json"},body:JSON.stringify({event_type:event,name,points,config:{minimum_bill:minimum}})});load();}
 if(!tenant)return <main className="shell"><div className="hero"><h1>Loading dashboard…</h1></div></main>;
 return <main className="shell"><section className="hero"><p>AI GROWTH OS • BUSINESS CONTROL CENTER</p><h1>{tenant.name}</h1><p>{tenant.industry} • Configure the customer experience without code.</p></section>
 <nav className="grid" style={{gridTemplateColumns:"repeat(auto-fit,minmax(110px,1fr))"}}>{["overview","features","menu","orders","requests","loyalty","reviews"].map(x=><button key={x} className="card" onClick={()=>setTab(x)}>{x==="overview"?"📊":x==="features"?"🎛️":x==="menu"?"📖":x==="orders"?"🍽️":x==="requests"?"🔔":x==="loyalty"?"🎁":"⭐"} {x}</button>)}</nav>
 {tab==="overview"&&<section className="grid"><article className="card"><h2>Customer experience</h2><p>{Object.values(features).filter(Boolean).length} enabled capabilities</p><button onClick={()=>setTab("features")}>Configure</button></article><article className="card"><h2>🍽️ Orders</h2><p>{orders.length} recent orders</p><button onClick={()=>setTab("orders")}>Open kitchen board</button></article><article className="card"><h2>🔔 Service</h2><p>{requests.filter(x=>x.status!=="completed").length} open requests</p><button onClick={()=>setTab("requests")}>Open service queue</button></article><article className="card"><h2>🎁 Loyalty</h2><p>{rules.length} earning rules</p><button onClick={()=>setTab("loyalty")}>Manage rewards</button></article></section>}
 {tab==="features"&&<section className="card"><h2>🎛️ Customer Experience</h2><p>Every tenant can turn modules on or off. AI follows these settings.</p><div className="grid">{Object.entries(featureLabels).map(([k,label])=><label className="card" key={k}><input type="checkbox" checked={features[k]!==false} onChange={e=>setFeatures({...features,[k]:e.target.checked})}/> {label}</label>)}</div><button onClick={saveFeatures}>Save feature settings</button></section>}
 {tab==="menu"&&<section className="card"><div style={{display:"flex",justifyContent:"space-between"}}><h2>📖 Menu Builder</h2><div><button onClick={addCategory}>+ Category</button><button onClick={addItem}>+ Item</button></div></div><div className="grid">{menu.items.map((x:any)=><article className="card" key={x.id}><h3>{x.name}</h3><p>{x.description||"No description"}</p><strong>₹{x.price}</strong><p>{x.is_available?"🟢 Available":"🔴 Sold out"}</p><button onClick={()=>toggleItem(x)}>{x.is_available?"Mark unavailable":"Mark available"}</button></article>)}</div></section>}
 {tab==="orders"&&<section className="card"><h2>🍽️ Live Order Board</h2>{orders.map((o:any)=><article className="card" key={o.id}><strong>#{o.id.slice(0,8)} • {o.context_token||"No table"}</strong><p>{o.items.map((i:any)=>i.quantity+"× "+i.name).join(", ")}</p><p>Total ₹{o.total} • <b>{o.status}</b></p><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{["confirmed","preparing","ready","assigned","served","completed","cancelled"].map(s=><button key={s} onClick={()=>orderStatus(o,s)}>{s}</button>)}</div></article>)}</section>}
 {tab==="requests"&&<section className="card"><h2>🔔 Live Service Requests</h2>{requests.map((x:any)=><article className="card" key={x.id}><strong>{x.request_type}</strong><p>{x.context_token||"No table"} • {x.message||"Customer needs assistance"}</p><p>Status: {x.status}</p>{x.status==="requested"&&<button onClick={()=>requestStatus(x,"acknowledged")}>Acknowledge</button>}{x.status==="acknowledged"&&<button onClick={()=>requestStatus(x,"in_progress")}>In progress</button>}{x.status==="in_progress"&&<button onClick={()=>requestStatus(x,"completed")}>Complete</button>}</article>)}</section>}
 {tab==="loyalty"&&<section className="card"><div style={{display:"flex",justifyContent:"space-between"}}><h2>🎁 Loyalty Rules</h2><button onClick={addRule}>+ Earning rule</button></div><p>Configure points from purchases, games, referrals and other events.</p>{rules.map((x:any)=><article className="card" key={x.id}><strong>{x.name}</strong><p>{x.event_type} → +{x.points} points</p>{x.config?.minimum_bill>0&&<small>Minimum bill ₹{x.config.minimum_bill}</small>}</article>)}</section>}
 {tab==="reviews"&&<section className="card"><h2>⭐ Google Review</h2><p>Paste the review link generated from your Google Business Profile.</p><input value={review} onChange={e=>setReview(e.target.value)} placeholder="https://..." /><button onClick={saveReview}>Save</button><p>Only genuine customer feedback should be directed to Google reviews; review incentives are not allowed by Google policy.</p></section>}
 <p aria-live="polite">{status}</p></main>;
}
