"use client";
import {useEffect,useRef,useState} from "react";
type Tenant={id:string;name:string;slug:string;industry?:string;description?:string;address?:string};
type Msg={who:string;text:string};
function bytesToB64(bytes:Uint8Array){let s="";for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s)}
function b64ToBytes(s:string){const b=atob(s);const o=new Uint8Array(b.length);for(let i=0;i<b.length;i++)o[i]=b.charCodeAt(i);return o}
function pcmToFloat(s:string){const b=b64ToBytes(s),f=new Float32Array(b.length/2),v=new DataView(b.buffer);for(let i=0;i<f.length;i++)f[i]=v.getInt16(i*2,true)/32768;return f}
export default function Customer(){
 const [slug,setSlug]=useState(""),[tenant,setTenant]=useState<Tenant|null>(null),[status,setStatus]=useState(""),[calling,setCalling]=useState(false),[handoff,setHandoff]=useState(false),[messages,setMessages]=useState<Msg[]>([]),[message,setMessage]=useState("");
 const wsRef=useRef<WebSocket|null>(null),signalRef=useRef<WebSocket|null>(null),streamRef=useRef<MediaStream|null>(null),ctxRef=useRef<AudioContext|null>(null),processorRef=useRef<ScriptProcessorNode|null>(null),pcRef=useRef<RTCPeerConnection|null>(null),remoteRef=useRef<HTMLAudioElement|null>(null),pollRef=useRef<number|undefined>(undefined),nextAudioRef=useRef(0);
 const base=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
 async function open(){const requested=new URLSearchParams(location.search).get("business");if(requested)setSlug(requested);const target=(requested||slug).trim().toLowerCase();const r=await fetch(base+"/api/v1/public/business/"+target);const d=await r.json();if(!r.ok){setStatus(d.detail||"Business not found");return}setTenant(d);setStatus("Ready to call")}
 function playPcm(s:string){const ctx=ctxRef.current;if(!ctx)return;const data=pcmToFloat(s),buf=ctx.createBuffer(1,data.length,24000);buf.copyToChannel(data,0);const src=ctx.createBufferSource();src.buffer=buf;src.connect(ctx.destination);const start=Math.max(ctx.currentTime,nextAudioRef.current);src.start(start);nextAudioRef.current=start+buf.duration}
 async function startAudio(){const stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}});streamRef.current=stream;const ctx=new AudioContext({sampleRate:16000});ctxRef.current=ctx;const source=ctx.createMediaStreamSource(stream),p=ctx.createScriptProcessor(4096,1,1);processorRef.current=p;p.onaudioprocess=e=>{const input=e.inputBuffer.getChannelData(0),out=new Int16Array(input.length);for(let i=0;i<input.length;i++){const x=Math.max(-1,Math.min(1,input[i]));out[i]=x<0?x*32768:x*32767}if(wsRef.current?.readyState===WebSocket.OPEN)wsRef.current.send(JSON.stringify({type:"audio",data:bytesToB64(new Uint8Array(out.buffer))}))};source.connect(p);p.connect(ctx.destination)}
 function stopAi(){try{wsRef.current?.send(JSON.stringify({type:"stop"}));wsRef.current?.close()}catch{}processorRef.current?.disconnect();streamRef.current?.getTracks().forEach(t=>t.stop());ctxRef.current?.close();wsRef.current=null}
 async function startHumanPeer(room:string){if(!tenant)return;setStatus("Connecting you to a staff member…");const ice=await fetch(base+"/api/v1/public/business/"+tenant.slug+"/voice/ice").then(r=>r.json());const pc=new RTCPeerConnection({iceServers:ice.ice_servers||[]});pcRef.current=pc;pc.ontrack=e=>{if(!remoteRef.current)return;remoteRef.current.srcObject=e.streams[0];remoteRef.current.play().catch(()=>{})};pc.onicecandidate=e=>{if(e.candidate&&signalRef.current?.readyState===WebSocket.OPEN)signalRef.current.send(JSON.stringify({type:"candidate",candidate:e.candidate}))};const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(t=>pc.addTrack(t,stream));const sws=new WebSocket(base.replace(/^http/,"ws")+"/ws/calls/"+room);signalRef.current=sws;sws.onmessage=async e=>{const m=JSON.parse(e.data);if(m.type==="offer"){await pc.setRemoteDescription(m.offer);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);sws.send(JSON.stringify({type:"answer",answer:pc.localDescription}))}else if(m.type==="candidate"&&m.candidate){try{await pc.addIceCandidate(m.candidate)}catch{}}else if(m.type==="staff_connected"){setStatus("Connected to staff member");setHandoff(true)}};sws.onopen=()=>sws.send(JSON.stringify({type:"customer_join"}))}
 async function checkHandoff(callId:string){if(!tenant)return;const d=await fetch(base+"/api/v1/public/business/"+tenant.slug+"/call/"+callId+"/handoff").then(r=>r.json());if(d.status==="handoff_requested"&&!handoff){setHandoff(true);stopAi();setStatus("Human handoff requested. Waiting for staff…");if(d.room_id)startHumanPeer(d.room_id)}if(d.status==="handoff_accepted"&&!handoff){setHandoff(true);stopAi();if(d.room_id)startHumanPeer(d.room_id)}if(d.status==="handoff_declined"||d.status==="handoff_unavailable"){setStatus("No staff member is available right now. AI/callback fallback can be used.");}}
 async function startCall(){if(!tenant)return;setCalling(true);setStatus("Connecting to AI…");setMessages([]);try{const r=await fetch(base+"/api/v1/public/business/"+tenant.slug+"/call",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Unable to create call");await startAudio();const ws=new WebSocket(base.replace(/^http/,"ws")+"/ws/public/voice/"+d.call_id);wsRef.current=ws;pollRef.current=window.setInterval(()=>checkHandoff(d.call_id),1500);ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==="status"){setStatus("AI connected");return}if(m.type==="transcript"){setMessages(x=>[...x,{who:m.role==="ai"?"AI":"You",text:m.text}]);return}if(m.type==="error"){setStatus(m.message);return}if(m.serverContent?.modelTurn?.parts)for(const part of m.serverContent.modelTurn.parts)if(part.inlineData?.mimeType?.startsWith("audio/pcm"))playPcm(part.inlineData.data)};ws.onopen=()=>setStatus("Connected — AI is answering");ws.onclose=()=>{if(!handoff)setStatus("AI call ended")}}catch(e:any){setCalling(false);setStatus(e.message||"Unable to start call")}}
 function endCall(){if(pollRef.current)window.clearInterval(pollRef.current);stopAi();signalRef.current?.close();pcRef.current?.close();streamRef.current?.getTracks().forEach(t=>t.stop());setCalling(false);setHandoff(false);setStatus("Call ended")}
 async function chat(){if(!tenant||!message)return;const r=await fetch(base+"/api/v1/public/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tenant_id:tenant.id,message,channel:"pwa"})});const d=await r.json();setMessages(m=>[...m,{who:"You",text:message},{who:"AI",text:d.reply||d.detail||"Unable to answer"}]);setMessage("")}
 useEffect(()=>()=>endCall(),[]);
 return <main className="shell"><div className="hero"><p>CUSTOMER PWA • AI VOICE + HUMAN HANDOFF</p><h1>{tenant?.name||"Business assistant"}</h1><p>{tenant?.description||"Connect instantly with the business AI assistant."}</p></div>{!tenant?<div className="card" style={{maxWidth:600,margin:"20px auto"}}><h2>Open business</h2><input placeholder="Business slug" value={slug} onChange={e=>setSlug(e.target.value)}/><button onClick={open}>Continue</button><p>{status}</p></div>:<div className="grid"><div className="card"><h2>📞 {handoff?"Live staff call":"Call "+tenant.name}</h2><p>{handoff?"Your AI conversation context is being transferred to the assigned staff member.":"AI answers first. If you request a person, the call can move to the assigned department without repeating your details."}</p>{!calling?<button onClick={startCall}>📞 Call now</button>:<button onClick={endCall}>🔴 End call</button>}<p>{status}</p><p>{tenant.address}</p><audio ref={remoteRef} autoPlay/></div><div className="card"><h2>{calling?"Live conversation":"AI Assistant"}</h2><div className="chat">{messages.map((m,i)=><p key={i}><b>{m.who}:</b> {m.text}</p>)}</div>{!calling&&<><textarea placeholder="Ask about services, prices or bookings" value={message} onChange={e=>setMessage(e.target.value)}/><button onClick={chat}>Send</button></>}</div></div>}</main>}
