"use client";
import {useEffect,useRef,useState} from "react";
type Tenant={id:string;name:string;slug:string;industry?:string;description?:string;address?:string};
type Msg={who:string;text:string};
function bytesToB64(bytes:Uint8Array){let s="";const step=0x8000;for(let i=0;i<bytes.length;i+=step)s+=String.fromCharCode(...bytes.subarray(i,i+step));return btoa(s)}
function b64ToBytes(s:string){const bin=atob(s);const out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
function pcmToFloat(b64:string){const b=b64ToBytes(b64);const f=new Float32Array(b.length/2);const v=new DataView(b.buffer);for(let i=0;i<f.length;i++)f[i]=v.getInt16(i*2,true)/32768;return f}
export default function Customer(){
 const [slug,setSlug]=useState("");const [tenant,setTenant]=useState<Tenant|null>(null);const [status,setStatus]=useState("");const [calling,setCalling]=useState(false);const [messages,setMessages]=useState<Msg[]>([]);const [message,setMessage]=useState("");
 const wsRef=useRef<WebSocket|null>(null);const streamRef=useRef<MediaStream|null>(null);const ctxRef=useRef<AudioContext|null>(null);const processorRef=useRef<ScriptProcessorNode|null>(null);const nextAudioRef=useRef(0);const base=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
 async function open(){const r=await fetch(base+"/api/v1/public/business/"+slug.trim().toLowerCase());const d=await r.json();if(!r.ok){setStatus(d.detail||"Business not found");return}setTenant(d);setStatus("Ready to call");}
 function playPcm(b64:string){const ctx=ctxRef.current;if(!ctx)return;const data=pcmToFloat(b64);const buf=ctx.createBuffer(1,data.length,24000);buf.copyToChannel(data,0);const src=ctx.createBufferSource();src.buffer=buf;src.connect(ctx.destination);const start=Math.max(ctx.currentTime,nextAudioRef.current);src.start(start);nextAudioRef.current=start+buf.duration;}
 async function startAudio(){const stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}});streamRef.current=stream;const ctx=new AudioContext({sampleRate:16000});ctxRef.current=ctx;const source=ctx.createMediaStreamSource(stream);const p=ctx.createScriptProcessor(4096,1,1);processorRef.current=p;p.onaudioprocess=e=>{const input=e.inputBuffer.getChannelData(0);const out=new Int16Array(input.length);for(let i=0;i<input.length;i++){const x=Math.max(-1,Math.min(1,input[i]));out[i]=x<0?x*32768:x*32767}if(wsRef.current?.readyState===WebSocket.OPEN)wsRef.current.send(JSON.stringify({type:"audio",data:bytesToB64(new Uint8Array(out.buffer))}))};source.connect(p);p.connect(ctx.destination);}
 async function startCall(){if(!tenant)return;setCalling(true);setStatus("Connecting to AI...");setMessages([]);try{const r=await fetch(base+"/api/v1/public/business/"+tenant.slug+"/call",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({})});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Unable to create call");await startAudio();const wsUrl=base.replace(/^http/,"ws")+"/ws/public/voice/"+d.call_id;const ws=new WebSocket(wsUrl);wsRef.current=ws;ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==="status"){setStatus("AI connected");return}if(m.type==="transcript"){setMessages(x=>[...x,{who:m.role==="ai"?"AI":"You",text:m.text}]);return}if(m.type==="error"){setStatus(m.message);return}if(m.serverContent?.modelTurn?.parts){for(const part of m.serverContent.modelTurn.parts)if(part.inlineData?.mimeType?.startsWith("audio/pcm"))playPcm(part.inlineData.data)}};ws.onopen=()=>setStatus("Connected — AI is answering");ws.onclose=()=>{setCalling(false);setStatus("Call ended")};}catch(e:any){setCalling(false);setStatus(e.message||"Unable to start call");}}
 function endCall(){try{wsRef.current?.send(JSON.stringify({type:"stop"}));wsRef.current?.close()}catch{}processorRef.current?.disconnect();streamRef.current?.getTracks().forEach(t=>t.stop());ctxRef.current?.close();setCalling(false);setStatus("Call ended");}
 async function chat(){if(!tenant||!message)return;const r=await fetch(base+"/api/v1/public/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tenant_id:tenant.id,message,channel:"pwa"})});const d=await r.json();setMessages(m=>[...m,{who:"You",text:message},{who:"AI",text:d.reply||d.detail||"Unable to answer"}]);setMessage("");}
 useEffect(()=>()=>endCall(),[]);
 return <main className="shell"><div className="hero"><p>CUSTOMER PWA • AI VOICE</p><h1>{tenant?.name||"Business assistant"}</h1><p>{tenant?.description||"Connect instantly with the business AI assistant."}</p></div>{!tenant?<div className="card" style={{maxWidth:600,margin:"20px auto"}}><h2>Open business</h2><input placeholder="Business slug" value={slug} onChange={e=>setSlug(e.target.value)}/><button onClick={open}>Continue</button><p>{status}</p></div>:<div className="grid"><div className="card"><h2>📞 Call {tenant.name}</h2><p>Tap once. Your browser connects directly to the AI voice assistant. The business mobile number is never displayed.</p>{!calling?<button onClick={startCall}>📞 Call now</button>:<button onClick={endCall}>🔴 End call</button>}<p>{status}</p><p>{tenant.address}</p></div><div className="card"><h2>{calling?"Live AI conversation":"AI Assistant"}</h2><div className="chat">{messages.map((m,i)=><p key={i}><b>{m.who}:</b> {m.text}</p>)}</div>{!calling&&<><textarea placeholder="Ask about services, prices or bookings" value={message} onChange={e=>setMessage(e.target.value)}/><button onClick={chat}>Send</button></>}</div></div>}</main>}
