"use client";
import {useEffect,useState} from "react";
const API=()=>process.env.NEXT_PUBLIC_API_URL||"https://ai-growth-os-api.onrender.com";
export default function KnowledgePage(){
  const [user,setUser]=useState<any>(null),[items,setItems]=useState<any[]>([]),[calls,setCalls]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{const raw=localStorage.getItem("ago_auth");if(!raw)return;try{const a=JSON.parse(raw);setUser(a?.user||null);if(a?.access_token&&a?.user?.tenant_id)load(a.access_token,a.user.tenant_id)}catch{}},[]);
  async function load(token:string,tenant:string){setBusy(true);setError("");try{const h={Authorization:"Bearer "+token};const [k,c]=await Promise.all([fetch(API()+"/api/v1/tenants/"+tenant+"/knowledge-candidates?status=pending",{headers:h}),fetch(API()+"/api/v1/tenants/"+tenant+"/call-logs?limit=50",{headers:h})]);const kj=await k.json(),cj=await c.json();if(!k.ok)throw new Error(kj.detail||"Unable to load knowledge candidates");setItems(kj.items||[]);setCalls(cj.items||[])}catch(e:any){setError(e?.message||"Unable to load knowledge intelligence.")}finally{setBusy(false)}}
  async function review(id:string,action:"approve"|"reject"){if(!user?.tenant_id)return;const raw=localStorage.getItem("ago_auth");if(!raw)return;const a=JSON.parse(raw);await fetch(API()+"/api/v1/tenants/"+user.tenant_id+"/knowledge-candidates/"+id+"/"+action,{method:"POST",headers:{Authorization:"Bearer "+a.access_token}});load(a.access_token,user.tenant_id)}
  return <main style={{padding:32,maxWidth:1200,margin:"0 auto"}}><h1>Knowledge & Voice Intelligence</h1><p>Every new question becomes a reviewable knowledge candidate. Approved answers move into the fast tenant library; call transcripts remain in CRM.</p>{error&&<p style={{color:"crimson"}}>{error}</p>}<section style={{marginTop:24}}><h2>Knowledge candidates {busy?"…":"("+items.length+")"}</h2>{items.length===0?<p>No pending knowledge gaps.</p>:items.map(x=><article key={x.id} style={{border:"1px solid #ddd",borderRadius:16,padding:20,margin:"12px 0"}}><strong>{x.question}</strong><p>{x.answer}</p><small>{x.language} · asked {x.times_asked} time(s) · {x.provider}</small><div style={{display:"flex",gap:8,marginTop:12}}><button onClick={()=>review(x.id,"approve")}>Approve to Knowledge Library</button><button onClick={()=>review(x.id,"reject")}>Reject</button></div></article>)}</section><section style={{marginTop:36}}><h2>Recent calls</h2>{calls.map(x=><article key={x.id} style={{borderBottom:"1px solid #eee",padding:"12px 0"}}><strong>Call #{x.call_number||"—"}</strong> · {x.language||"en"} · {x.resolution||x.status||"—"} · {x.duration_seconds||0}s<div><small>{x.transcript||"No transcript yet."}</small></div></article>)}</section></main>;
}