"use client";
import {useEffect,useState} from "react";
const api=()=>process.env.NEXT_PUBLIC_API_URL||"https://ai-growth-os-api.onrender.com";
export default function Platform(){
 const [items,setItems]=useState<any[]>([]),[status,setStatus]=useState(""),[notification,setNotification]=useState<any>(null),[showPassword,setShowPassword]=useState(false),[form,setForm]=useState<any>({business_name:"",slug:"",industry:"wellness",owner_name:"",owner_email:"",owner_password:"",phone:"",whatsapp_number:"",address:""});
 const token=()=>localStorage.getItem("ago_access_token")||"";
 async function load(){try{const accessToken=token();if(!accessToken){window.location.href="/login";return}const r=await fetch(api()+"/api/v1/platform/tenants",{headers:{Authorization:"Bearer "+accessToken},cache:"no-store"});const raw=await r.text();let x:any={};try{x=JSON.parse(raw)}catch{}if(r.status===401||r.status===403){window.location.href="/login";return}if(!r.ok){setStatus(x?.detail||"Unable to load tenants");return}setItems(Array.isArray(x?.items)?x.items:[])}catch{setStatus("Unable to connect to the platform service.")}}
 useEffect(()=>{load()},[]);
 async function provision(e:any){e.preventDefault();setStatus("Provisioning business...");setNotification(null);try{const r=await fetch(api()+"/api/v1/platform/tenants/provision",{method:"POST",headers:{Authorization:"Bearer "+token(),"Content-Type":"application/json"},body:JSON.stringify(form)});const raw=await r.text();let x:any={};try{x=JSON.parse(raw)}catch{}if(r.status===401||r.status===403){window.location.href="/login";return}if(!r.ok){setStatus(x?.detail||"Provisioning failed");return}setNotification(x.notifications||null);setStatus("Tenant activated: "+x.tenant.name+" • owner login "+x.owner.email);setForm({business_name:"",slug:"",industry:"wellness",owner_name:"",owner_email:"",owner_password:"",phone:"",whatsapp_number:"",address:""});setShowPassword(false);void load()}catch{setStatus("Unable to reach the platform service.")}}
 return <main className="shell"><section className="hero"><p>AI GROWTH OS • PLATFORM SUPER ADMIN</p><h1>Business Provisioning Center</h1><p>Create and activate a complete tenant in one flow.</p></section>
 <section className="card"><h2>+ Provision New Tenant</h2><form onSubmit={provision} className="grid">
 {["business_name","slug","owner_name","owner_email","owner_password","phone","whatsapp_number","address"].map(k=><label key={k}>{k.replaceAll("_"," ")}<input required={["business_name","slug","owner_name","owner_email","owner_password"].includes(k)} type={k==="owner_password"?(showPassword?"text":"password"):k==="owner_email"?"email":"text"} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>{k==="owner_password"&&<button type="button" onClick={()=>setShowPassword(!showPassword)}>{showPassword?"Hide":"Show"}</button>}</label>)}
 <label>Industry<select value={form.industry} onChange={e=>setForm({...form,industry:e.target.value})}>{["wellness","health","dental","restaurant","hotel","salon","gym","real-estate","education"].map(x=><option key={x}>{x}</option>)}</select></label>
 <button type="submit" disabled={form.owner_password.length<8}>Create & Activate Tenant</button></form><p>{status}</p>{notification&&<div className="card"><h3>Confirmation delivery</h3><p>Email: {notification.email?.status||"unknown"}{notification.email?.sent?" ✓":""}</p><p>WhatsApp: {notification.whatsapp?.status||"unknown"}{notification.whatsapp?.sent?" ✓":""}</p></div>}</section>
 <section className="card"><h2>Tenants</h2>{items.map(t=><article className="card" key={t.id}><strong>{t.name}</strong><p>{t.industry} • {t.slug} • {t.status}</p></article>)}{!items.length&&<p>No tenants yet.</p>}</section></main>;
}