FAQS = [
("general","en","hours","What are your opening hours?","Please check the business hours configured by the business.","hours open timing"),
("general","en","location","Where are you located?","Our location is shown in the business profile and directions section.","location address directions"),
("general","en","contact","How can I contact you?","You can contact the business using the phone or WhatsApp details shown in its profile.","contact phone whatsapp"),
("general","en","booking","How do I book an appointment?","Ask the assistant for the service and preferred date/time. The booking system will confirm availability before a booking is created.","book appointment schedule reserve"),
("general","en","cancel","Can I cancel my booking?","Cancellation depends on the business policy. The assistant can check the configured policy or route you to staff.","cancel cancellation booking"),
("general","en","payment","What payment methods do you accept?","Available payment methods are those configured by the business. Payment success is confirmed by the payment system.","payment pay card cash upi"),
("general","en","refund","How do refunds work?","Refunds follow the business's configured refund policy. The assistant will not promise a refund without confirmation.","refund return money"),
("general","en","whatsapp","Can I contact you on WhatsApp?","Yes, if WhatsApp is enabled for this business, use the WhatsApp button in the customer experience.","whatsapp message"),
("general","en","human","Can I speak to a person?","Yes. The AI can collect the context and route the conversation to the appropriate team.","human staff agent person"),
("general","en","price","What is the price?","Prices come from the business's configured services and products. Ask for a specific service or product.","price cost fee rate"),
("dental","en","appointment","Do I need an appointment for a dental visit?","Appointment requirements are set by the dental practice. The assistant can check its configured booking rules.","dentist dental appointment visit"),
("dental","en","emergency","Do you handle dental emergencies?","The practice's emergency policy determines available support. The assistant can route an urgent request to the practice.","dental emergency urgent tooth"),
("dental","en","cleaning","Do you offer dental cleaning?","If dental cleaning is configured as a service, the assistant can provide its configured details and booking options.","cleaning teeth hygiene"),
("hotel","en","checkin","What time is check-in?","Check-in time is determined by the hotel's configured policy.","hotel check in arrival"),
("hotel","en","checkout","What time is check-out?","Check-out time is determined by the hotel's configured policy.","hotel check out departure"),
("hotel","en","room","What room types are available?","Room types and availability are provided from the hotel's configured inventory and booking system.","room rooms suite availability"),
("restaurant","en","menu","Can I see the menu?","The customer experience can show the restaurant's configured menu and products.","menu food dishes restaurant"),
("restaurant","en","delivery","Do you offer delivery?","Delivery availability depends on the restaurant's configured service area and delivery settings.","delivery takeaway food"),
("salon","en","services","What services does the salon offer?","The assistant can list the salon's configured services and prices.","salon haircut beauty services"),
("gym","en","membership","What membership plans do you offer?","Membership plans and prices come from the gym's configured products or services.","gym membership fitness plans"),
("real_estate","en","property","What properties do you have?","Available properties can be shown from the business's configured property inventory.","property house flat rent sale"),
("education","en","course","What courses do you offer?","Courses and fees come from the education business's configured catalog.","course class coaching education"),
("automotive","en","service","What vehicle services do you provide?","The workshop's configured service catalog contains available vehicle services.","car vehicle service repair"),
("wellness","en","consultation","Do you offer consultations?","Consultation availability depends on the wellness business's configured services and booking rules.","wellness consultation health"),
("retail","en","shipping","Do you provide delivery?","Delivery options depend on the store's configured delivery settings.","retail shipping delivery order"),
]
