"use client";
import {useEffect,useState} from "react";
const api=()=>process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
const defaults={eyebrow:"MOINABAD · RANGAREDDY · TELANGANA",hero_title:"Feel better.",hero_emphasis:"Live consciously.",hero_description:"Practical wellness for modern life, with an organic-focused approach to healthier everyday choices.",about_title:"Health consciousness starts with what you do every day.",about_text:"SS Nutritions is a local wellness brand based in Moinabad, focused on helping people make informed, sustainable lifestyle choices.",whatsapp_number:"",contact_heading:"Your wellness journey can start with one conversation.",contact_text:"Tell us what you are looking for and our team can guide you on the next step.",quote:"Wellness is not about changing everything overnight. It is about making better choices, consistently.",published:true};
export default function WebsiteEditor(){const [tenant,setTenant]=useState<any>(null),[v,setV]=useState<any>(defaults),[status,setStatus]=useState("");const token=()=>localStorage.getItem("ago_access_token")||"";const h=()=>({Authorization:"Bearer "+token()});
useEffect(()=>{const raw=localStorage.getItem("ago_tenant");if(!raw){location.href="/login";return}const t=JSON.parse(raw);setTenant(t);fetch(api()+"/api/v1/tenants/"+t.id+"/website",{headers:h()}).then(r=>r.ok?r.json():defaults).then(setV)},[]);
const set=(k:string,x:string|boolean)=>setV((p:any)=>({...p,[k]:x}));
async function save(){if(!tenant)return;const r=await fetch(api()+"/api/v1/tenants/"+tenant.id+"/website",{method:"PUT",headers:{...h(),"Content-Type":"application/json"},body:JSON.stringify(v)});setStatus(r.ok?"Published successfully. Changes are now available on the public website.":"Could not save website content.")}
return <main className="shell"><section className="hero"><p>AI GROWTH OS • SS NUTRITIONS</p><h1>Website Control Center</h1><p>Edit your public website without touching code.</p></section><section className="card"><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",alignItems:"center"}}><div><h2>Website content</h2><p>These fields control the SS Nutritions landing page. Save once and the live page reads the tenant settings.</p></div><a className="button" href="/ss-nutritions" target="_blank">Open live site ↗</a></div><div className="grid">{[["eyebrow","Top label"],["hero_title","Hero title"],["hero_emphasis","Hero emphasis"],["hero_description","Hero description"],["about_title","About heading"],["about_text","About text"],["whatsapp_number","WhatsApp number"],["contact_heading","Contact heading"],["contact_text","Contact text"],["quote","Brand quote"]].map(([k,l])=><label key={k}>{l}{["hero_description","about_title","about_text","contact_heading","contact_text","quote"].includes(k)?<textarea value={v[k]||""} onChange={e=>set(k,e.target.value)}/>:<input value={v[k]||""} onChange={e=>set(k,e.target.value)}/>}</label>)}</div><label className="card"><input type="checkbox" checked={!!v.published} onChange={e=>set("published",e.target.checked)}/> Publish website content</label><button onClick={save}>Save & publish</button>{status&&<p>{status}</p>}</section><section className="card"><h2>What you can update here</h2><div className="grid"><article><h3>✍️ Messaging</h3><p>Hero, about, contact and brand quote.</p></article><article><h3>💬 WhatsApp</h3><p>Store the business WhatsApp number for customer contact flows.</p></article><article><h3>📱 PWA</h3><p>The same SS Nutritions site remains installable as a mobile PWA.</p></article></div></section></main>}
